const gallery = [
  { src: "/images/models/ciaz/1.png", width: 800, height: 600 },
  { src: "/images/models/baleno/1.jpeg", width: 1600, height: 900 },
  { src: "/images/models/ciaz/1.png", width: 1600, height: 900 },
  { src: "/images/models/baleno/1.jpeg", width: 1600, height: 900 },
  {
    id: 1,
    href: "#",
    src: "/images/models/swift/1.png",
    name: "New Swift",
    logo: "/images/swiftlogo.png",
    width: 800,
    height: 600,
  },
  {
    id: 2,
    href: "#",
    src: "/images/models/celerio/1.png",
    name: "Beleno",
    logo: "/images/celeriologo.png",
    width: 800,
    height: 600,
  },
  {
    id: 3,
    href: "#",
    src: "/images/models/ciaz/1.png",
    name: "CIAZ",
    logo: undefined,
    width: 800,
    height: 600,
  },
  {
    id: 4,
    href: "#",
    src: "/images/models/baleno/1.jpeg",
    name: "Celerio",
    logo: "/images/celeriologo.png",
    width: 800,
    height: 600,
  },
  {
    id: 5,
    href: "#",
    src: "/images/models/ertiga/1.webp",
    name: "Ertiga",
    logo: undefined,
    width: 800,
    height: 600,
  },
  {
    id: 6,
    href: "#",
    src: "/images/models/jimny/1.png",
    name: "Jimny",
    logo: "/images/jemnylogo.png",
    width: 800,
    height: 600,
  },
  {
    id: 7,
    href: "#",
    src: "/images/models/spresso/1.png",
    name: "S-presso",
    logo: undefined,
    width: 800,
    height: 600,
  },
  {
    id: 8,
    href: "#",
    src: "/images/models/swift/2.webp",
    name: "Ertiga",
    logo: "/images/swiftlogo.png",
    width: 800,
    height: 600,
  },
  {
    id: 9,
    href: "#",
    src: "/images/models/jac/1.webp",
    name: "JAC",
    logo: "/images/jaclogo.png",
    width: 800,
    height: 600,
  },
  {
    id: 10,
    href: "#",
    src: "/images/models/jac/2.webp",
    name: "JAC",
    logo: "/images/jaclogo.png",
    width: 800,
    height: 600,
  },
  {
    id: 11,
    href: "#",
    src: "/images/models/vitara/1.webp",
    name: "VITARA",
    logo: undefined,
    width: 800,
    height: 600,
  },
];

export default gallery;
