export const carsData = [
  {
    id: 1,
    href: "#",
    image: "/images/models/swift/1.png",
    name: "New Swift",
    logo: "/images/swiftlogo.png",
  },
  {
    id: 2,
    href: "#",
    image: "/images/models/celerio/1.png",
    name: "Beleno",
    logo: "/images/celeriologo.png",
  },
  {
    id: 3,
    href: "#",
    image: "/images/models/ciaz/1.png",
    name: "CIAZ",
    logo: undefined,
  },
  {
    id: 4,
    href: "#",
    image: "/images/models/baleno/1.jpeg",
    name: "Celerio",
    logo: "/images/celeriologo.png",
  },
  {
    id: 5,
    href: "#",
    image: "/images/models/ertiga/1.webp",
    name: "Ertiga",
    logo: undefined,
  },
  {
    id: 6,
    href: "#",
    image: "/images/models/jimny/1.png",
    name: "Jimny",
    logo: "/images/jemnylogo.png",
  },
  {
    id: 7,
    href: "#",
    image: "/images/models/spresso/1.png",
    name: "S-presso",
    logo: undefined,
  },
  {
    id: 8,
    href: "#",
    image: "/images/models/swift/2.webp",
    name: "Ertiga",
    logo: "/images/swiftlogo.png",
  },
];
